name: CI Pipeline  

on:  
  push:  
    branches:  
      - main  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Greet DevOps  
        run: echo "Hello, DevOps!"  

  deploy:  
    runs-on: ubuntu-latest  
    needs: build  

    steps:  
      - name: Deployment Message  
        run: echo "Deployment Successful!"  